[package]

name = "rcopy"
version = "0.0.1"
authors = ["Adam Wright <adam.austin.wright@gmail.com>"]

[[bin]]
name = "rcopy"
path = "src/bin/rcopy.rs"

[[bin]]
name = "rcopyd"
path = "src/bin/rcopyd.rs"
